services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - "6379:6379"
    command: redis-server --requirepass $REDIS_PASSWORD

  encore:
    build: .
    container_name: encore_backend
    ports:
      - "4000:4000"
      - "9400:9400"
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "4000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - encore
    networks:
      - app_network

networks:
  app_network:
    driver: bridge